### ISSUE TITLE
Trojans reported in LameXP-RC11.2021-07-26.Release-Static.Build-2317 and LameXP-RC5.2021-04-22.Release-Static.Build-2305

### ISSUE THREAD

**Issue by highqualitymusic** [lordmulder/LameXP#100]
Kaspersky and some others report 

• Trojan.Win32.Injuke.esnd  in LameXP of LameXP-RC5.2021-04-22.Release-Static.Build-2305
and
• Trojan.Win32.Generic (heuristic) in LameXP-RC11.2021-07-26.Release-Static.Build-2317 
in detail: lxp_curl.exe and lxp_verify.exe which are put into TEMP-Folder when starting LameXP.exe by its DebugConsole in CMD Window. 

The original verify.exe and the curl.exe are free of viruses, I checked them by virustotal.

exe and zip file were downloaded from the link you recommended 
https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2021-07-26/

To get rid of annoying and "YOU MUST UPDATE ME" I tried these Beta versions. 

 :-/
 
Kaspersky AntiVirus (actual signature data base) reports:
Typ: Trojan
Name: Trojan.Win32.Injuke.esnd
Genauigkeit: Genau
Bedrohungsstufe: Hoch
Objekttyp: Datei
Objektname: LameXP.exe
Objektpfad: C:\Program Files (x86)\LameXP
SHA256: F0B052E06BB4B139712C08B5B63E382AD24180D854BE8B0CEB641A920BF8EEEC
MD5: A1DE7D58430D1231D1B803D902016006

Name: HEUR:Trojan.Win32.Generic
Genauigkeit: Teilweise
Bedrohungsstufe: Hoch
Objekttyp: Datei
Objektname: lxp_curl.exe
Objektpfad: R:\TEMP\2083483c74bb12c4
MD5: D8BF68E5EE7B3EF5AA19BA943C5C55FC

Name: HEUR:Trojan.Win32.Generic
Genauigkeit: Teilweise
Bedrohungsstufe: Hoch
Objekttyp: Datei
Objektname: lxp_verify.exe
Objektpfad: R:\TEMP\2083483c74bb12c4
MD5: 1CD79727442DF5A01967EB872C21551B

**I could not check this by virustotal since the TEMP folder is occupied and acces denied for regular admin and I would need to access/copy these files out of this folder with system or root rights which I do not dare.**

**Comment by lordmulder** [comment]
👉 http://lamexp.sourceforge.net/doc/Manual.html#anti-virus-notes

And please do *not* cross-post.

**Comment by highqualitymusic** [comment]
Thank you for your detailled infomation! :smiley: :+1: 
What about the Trojan.Win32.Injuke.esnd ? 

I think, this cross posting **is** useful to inform other users who switch to the Beta for the same reason like me or for different ones.
False positive alerts are alerts nonetheless, they will happen to other users and will be quite unsettling for them. This will make them avoid beta versions and make them more likely to stick with an old / outdated version. That's exactly what you don't want, isn't it?!
It is not easy for the common user to check out and upload these files since access is blocked.

**Comment by lordmulder** [comment]
>  What about the Trojan.Win32.Injuke.esnd ?

I have no idea. It's just an arbitrary code-name the "anti-virus" vendor has assigned to one of the many thousands of "threats" they have in their database. And only ***they*** could tell why this specific one **mistakenly** happens to match to my software. Provided that they would care to figure out – which, of course, they don't.

> False positive alerts are alerts nonetheless, they will happen to other users and will be quite unsettling for them.

It will only be unsettling for those users who haven't yet understood that the business model of so-called "anti-virus" software is based on fear and misinformation.

> This will make them avoid beta versions and make them more likely to stick with an old / outdated version. 

The chance of seeing false positives is no bigger (or smaller) in "beta" versions than in "stable" versions. In theory, a "stable" version should be deployed on more machines, so has a higher chance ending up on the anti-virus vendor's whitelist. But, in reality, a software project like *this* is **way** too "insignificant" that any anti-virus vendor would bother...
