### ISSUE TITLE
Meta data Artist Tags not filled in properly

### ISSUE THREAD

**Issue by lamexpuser1** [lordmulder/LameXP#107]
The converter from flac to mp3 does not always transfer meta data correctly:
1) Album artist is not copied from source and is blank
2) Contributing artist is not copied from source but is filled in with data from unknown source

See property file attachments for examples.

![hello flac](https://user-images.githubusercontent.com/107070382/172452071-c7450f06-32f1-4d70-8488-57de4b82741b.jpg)
![hello mp3](https://user-images.githubusercontent.com/107070382/172452076-c689c7d3-65ae-4905-a589-92dff6fe3359.jpg)
.

**Comment by lordmulder** [comment]
Hallo,

LameXP supports a large number input/output formats. The _internal_ meta-data model was designed to cover what is supported by most formats. So, we have "Artist", but **not** separately "Album Artist". Sorry about that.

Regards.

**Comment by lamexpuser1** [comment]
I checked the properties with Media Monkey and VLC.  What Windows file properties calls "Contributing Artist", MM calls "Artist(s)" and VLC calls "Artist".  Note the "Artist" field is not copied properly by the FLAC to MP3 converter.  Any explanation for the discrepancy? Please see attachments. Unfortunately, this app did not allow me to attach the mp3 and flac files.

![hello media monkey flac properties](https://user-images.githubusercontent.com/107070382/174492587-64f51bde-259a-4985-88b2-5a7e4389a1fa.jpg)
![hello media monkey mp3 properties](https://user-images.githubusercontent.com/107070382/174492588-674b5de5-b8b9-403c-939e-4a4c827654f3.jpg)
![hello vlc flac properties](https://user-images.githubusercontent.com/107070382/174492589-6e010fcd-b6c9-4255-8645-6fd4f6a2bf55.jpg)
![hello vlc mp3 properties](https://user-images.githubusercontent.com/107070382/174492590-a3dd01b8-1917-44b2-a2eb-c3b9b7001f6e.jpg)

**Comment by lamexpuser1** [comment]
Here are the metadata from the Switch+ app:
![hello switch flac properties](https://user-images.githubusercontent.com/107070382/174493079-292715d6-eeaa-4d9c-9f86-31624b5f68b7.jpg)
![hello switch mp3 properties](https://user-images.githubusercontent.com/107070382/174493080-57aeb755-59f2-4a9d-9a93-be4bae264c82.jpg)

**Comment by lordmulder** [comment]
Can please check the original input file with **[MediaInfo](https://github.com/lordmulder/mediainfo-gui/releases/tag/v2.41)**?

Note: You can see which meta tags LameXP has detect (via MediaInfo) by looking at the file's properties after importing it:

![grafik](https://user-images.githubusercontent.com/470590/174493298-fd9f6487-74ed-4dcf-9510-da33369914f0.png)

**Comment by lamexpuser1** [comment]
I unzipped the files on Windows 10.  I tried to execute all five exe files and nothing starts, just a momentary (100 msec) dialog box flash.  Can I send you the original mp3 and flac files?

**Comment by lordmulder** [comment]
If you use CLI version of MediaInfo, you have to run from the command prompt (`cmd.exe`) the following command:
```
MediaInfo.exe "c:\path\to\your\file.mp3"
```

**Comment by lamexpuser1** [comment]
Here is the output from MediaInfo-GUI.2022-04-18.zip. I did not get the same output as your example.  Appears to be using the "performer" field.  Should be "ARTISTS"?

![hello flac mediainfo-gui 2022-04-18](https://user-images.githubusercontent.com/107070382/174499246-236c0b86-1ebd-4ad8-907b-ee82e84fb4ad.jpg)
![hello mp3 mediainfo-gui 2022-04-18](https://user-images.githubusercontent.com/107070382/174499248-455ce6f3-cd6f-4f05-8255-bae17ddc4875.jpg)

**Comment by lordmulder** [comment]
Again, different file formats support different tags. And sometimes the same information (more or less) goes by different names, like "artist", "album artist" or "performer". LameXP uses MediaInfo to extract the meta tags from the original input file and then tries to map the available to a small set of ***standard*** tags, which we will be able to pass on the selected encoder.

Do I understand correctly that the FLAC  is your original input file? As far as I see, this one has a "performer" tag. If you add that file to LameXP, then I think "performer" should be mapped to "artist". So what exactly shows up as "artist" in LameXP?

**Comment by lamexpuser1** [comment]
The other applications are using the media info "ARTISTS" field, not the "performer" field.

**Comment by lordmulder** [comment]
Yeah, different name for same/similar thing.

Can you please just drop the **original** unmodified FLAC file into LameXP, click "Show Details" and post the result?

**Comment by lamexpuser1** [comment]
I can send you the original files.

![hello flac LameXP](https://user-images.githubusercontent.com/107070382/174669558-1a8e8002-f11c-4095-a4dd-84f4c027a6f9.jpg)

**Comment by lordmulder** [comment]
Please show output of "Show Details" for input file "01 Hello.flac" on "Source Files" tab, **not** "Meta Data" tab.

**Comment by lamexpuser1** [comment]
![hello flac details](https://user-images.githubusercontent.com/107070382/174851086-7d65ca70-1211-4c0f-95f5-4c8d1cdf8175.jpg)

**Comment by lordmulder** [comment]
So, after all, LameXP (via MediaInfo) correctly detects the "Artist" for this file.

LameXP will pass the information to the MP3 encoder. And, as we can see from your earlier MediaInfo screenshot, there is a corresponding "Performer" (a.k.a. "Artist") tag present in the generated MP3 file. Don't see a problem here....

**Comment by lamexpuser1** [comment]
The four other applications documented above are using the media info "ARTISTS" field, not the "performer" field for the band name. In my automobile, on the playback screen for the converted MP3 song, the band displayed for the song is listing the members of the band and not the band name "Adele".

**Comment by lordmulder** [comment]
As said before, different applications may use different names for the same/synonymous tags.

Also, even more important, LameXP uses the **LAME** mp3 encoder. The following meta tags can be passed to LAME:

> ### ID3 tag Information
> **`--tt title`** Audio/song title (max 30 chars for version 1 tag)
> **`--ta artist`** Audio/song artist (max 30 chars for version 1 tag)
> **`--tl album`** Audio/song album (max 30 chars for version 1 tag)
> **`--ty year`** Audio/song year of issue (1 to 9999)
> **`--tc comment`** User-defined text (max 30 chars for v1 tag, 28 for v1.1)
> **`--tn track`** Audio/song track number and (optionally) the total number of tracks on the original recording.
> **`--tg genre`** Audio/song genre (name or number in list)
> **`--ti file`** Audio/song albumArt (jpeg/png/gif file, 128KB max, v2.3)

**Comment by lamexpuser1** [comment]
OK, so pass what mediainfo calls the "ARTISTS" field from the flac file to MP3 encoder for the "artist" field.  Then LameXP will be in agreement with four other applications.

**Comment by lordmulder** [comment]
Well, that is exactly what happens, I think.

Whatever has been detected as Artist/Performer from the original file will be passed to the MP3 encoder **`--ta`** option.

You can double check by double-clicking on the item in the encoder window and see the actual command-line.

**Comment by lamexpuser1** [comment]
The attachment displays the meta information for the flac file.  Clearly, the "performer" field from the FLAC file is copied into the ARTIST field.  LAMEXP should use the media info field ARTISTS instead.

![hello flac meta information](https://user-images.githubusercontent.com/107070382/175644693-db244834-ce1b-4590-888a-e009f28cc702.jpg)

**Comment by lordmulder** [comment]
I think this discussion is going in circles. As explained before, neither LameXP has a distinction between "Artist" or "Performer" (or whatever you like to call it) in its **_internal_** meta data model, nor does the LAME mp3 encoder have options to set "Artist" and "Performer" separately (there only is the **`--ta`** option to set what LAME calls "Artist" meta tag).

**Comment by lamexpuser1** [comment]
I have five applications documented above.  Four of the applications display the artist field as "Adele".  LameXP meta information (above) displays the artist as a different value, namely the band members. Clearly, LameXP has extracted the incorrect Artist field from the flac file.   The MP3 conversion is not relevant at this point; the MP# converter is storing the incorrect data supplied by LameXP in the artist field so that conversion is working properly.  The problem is LameXP is obviously extracting the incorrect field for the artist name.  LameXP needs to use the correct field from the flac file for input into the MP3 converter, defined in media info as the "ARTISTS" field, not the incorrect "performers" field. The name is irrelevant for our purposes but clearly LameXP need to extract the "ARTISTS" field to be in agreement with the other four applications.   If LameXP was in agreement with the four other applications then the meta information would display "Adele" for the artist not the band members.  The net effect is on playback, the media display shows the band members which obviously is NOT the artist, rather than Adele which appears as the artist when playing the flac file.  Seems straight forward really.  I have approximately 1000 CDs converted and a substantial percentage are showing the incorrect artist.  I can send you the files.
