### ISSUE TITLE
Any potential clash with Apple software?

### ISSUE THREAD

**Issue by iRamble88** [lordmulder/LameXP#108]
I don't know if this is the right place to ask this... not even sure how to ask it correctly so please go easy on me. 

Is there anything relating to Apple in this download that could somehow negatively affect Apple's software? I'll spare everyone specific details and don't want this post to troubleshoot my Apple/iTunes/iPhone issues but I am having an issue and have gone through the forums and customer service and everything to no avail and am obviously pulling at straws. 

I am only asking here because this is the only thing I have installed on a new laptop that I can find any any association with Apple/iTunes (prob didn't say that right)...   originally downloaded this on a different machine and used it, at least partially, to convert Apple/iTunes files (works great btw) and there is nothing else on the new laptop, besides this, that I can find having any association with iTunes. 

I  am not knowledgeable enough on the tech side to understand any of the information I find when I try to search for this question/answer that I am trying to ask... My brain taps out with words like "dependency, resource contention, clash detection, environment conflict, version control" which is what I see when I try to find an answer on my own... I don't know how any of it works or why or how anything does what it does and saw AppleApplicationSupport somewhere in the LameXP manual or troubleshooting or in my filesystem. That's the only connection between the two that I can find but that's at least one more connection than any other software I have installed that I'm able to find. So that has brought me to this point.

I feel like the question I'm failing to articulate is likely a dumb question and I do apologize for being double dumb but I have to try. Any help would be greatly appreciated.

**Comment by lordmulder** [comment]
No, I can **not** think of a way how LameXP could "clash" with Apple software 🤔

LameXP _optionally_ can use the _QAAC_ MP4 encoder, which uses the Apple AAC encoder library and therefore requires the "Apple Application Support" package to be installed. But this is totally optional and **not** installed by default.

**Comment by iRamble88** [comment]
Appreciate the reply

-ARay
