### ISSUE TITLE
Update check fails to complete successfully.

### ISSUE THREAD

**Issue by fishnet37222** [lordmulder/LameXP#111]
I'm running version 4.19 and every time I launch the app, it prompts me to check for an update.  I click the button to allow it to check, but it never completes the check.  I've attached the log file.

[lamexp-update-log.txt](https://github.com/lordmulder/LameXP/files/10905710/lamexp-update-log.txt)

**Comment by lordmulder** [comment]
Should be fixed by now 😎

**Comment by fishnet37222** [comment]
I just tried and it is working again.  Thanks.
