### ISSUE TITLE
GURU MEDITATION: Unhandeled Exception Handler Invoked, application will exit!

### ISSUE THREAD

**Issue by Meguido** [lordmulder/LameXP#117]
Hello, 
I'm getting the error window pop-up with the text mentioned in the Title, right after executing the app and so it closes right after that. I tried with the latest version and some others with the same result. Tried with the installer .exe version and the .zip portable one and always the same result.

What's causing this error? I mean, there's no other info about it and the text it's pretty ambiguous.

Regards.

**Comment by lordmulder** [comment]
Well, it means that the application has "crashed" because of an underhanded exception.

It's hard to guess what might be the problem without additional information.

1. What operating system and CPU are you running on?
2. Does running LameXP with parameter [`--console`](https://lamexp.sourceforge.net/doc/Manual.html#diagnostic-output) give any additional hints?
3. Do you have any so-called "anti-virus" software (other than the standard Windows Defender) installed?
   If so, try *uninstalling* completely, reboot and check if it makes any difference – just to be sure.
4. Is this a "new" problem/regression with version 4.21? For example, does version 4.20 work okay for your?

**Comment by Meguido** [comment]
Ok, additional info incoming

1. I'm using Windows 10 x64 (v. 21H2) and my CPU is AMD Ryzen 9 7950X
2. Running it with the param --console throws some warnings (don't know if related or not)

> Failed to resolve function: ntdll::wine_get_version
> SetConsoleIcon() has failed! [Error: 0x00004001]
> NeroAAC encoder binaries not found -> Encoding support will be disabled!
> QAAC encoder binaries not found -> Encoding support will be disabled!
> FhgAacEnc encoder binaries not found -> Encoding support will be disabled!
> FdkAacEnc encoder binaries not found -> Encoding support will be disabled!
> QAACx64 encoder binaries not found -> Encoding support will be disabled!

3. I have ESET Endpoint as anti-virus. I tried uninstalling it, rebooting and executing this again with no new result
4. I tried from 4.14 up to the lates release, all with the same error 
5. It started loading a lot of stuff to just sit there in a white screen like a frozen window and it's doing nothing since then. Found this on the command window in Windows Debugger:
```
(4528.2688): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=080734bc ebx=00000000 ecx=06c81964 edx=080734bc esi=06c81960 edi=0000000c
eip=7446408f esp=0780fb98 ebp=0780fc10 iopl=0         nv up ei ng nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010286
WINMM!soundInitWavHdr+0x20:
7446408f 813852494646    cmp     dword ptr [eax],46464952h ds:002b:080734bc=????????
```

**Comment by lordmulder** [comment]
> Running it with the param --console throws some warnings (don't know if related or not)
> ```
> …
> QAACx64 encoder binaries not found -> Encoding support will be disabled!
> ```

Is that really the last output line before the crash?

---

> I tried from 4.14 up to the lates release, all with the same error

That is really weird. It means that it's certainly **not** a new issue (or regression) in the latest release.

On the other hand, I have **not** seen this problem on any of my machines, nor has anybody reported a similar issue 🤔 

So this would indicate some sort of "anomaly" on your specific system...

---

> Found this on the command window in Windows Debugger:
> ```
> (4528.2688): Access violation - code c0000005 (first chance)
> First chance exceptions are reported before any exception handling.
> This exception may be expected and handled.
> eax=080734bc ebx=00000000 ecx=06c81964 edx=080734bc esi=06c81960 edi=0000000c
> eip=7446408f esp=0780fb98 ebp=0780fc10 iopl=0         nv up ei ng nz na pe nc
> cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010286
> WINMM!soundInitWavHdr+0x20:
> 7446408f 813852494646    cmp     dword ptr [eax],46464952h ds:002b:080734bc=????????
> ```

"Access violation" is a rather generic error. It simply means that the program, in one way or another, tried to access a "bad" (e.g. invalid or inaccessible) memory address. There's like a multitude of ways how this might happen...

Anyway, `WINMM!soundInitWavHdr` gives some hint that is may actually be related to _**sound**_ output 🤓 

Can you please try edit your **`config.ini`** like this and see if it makes any difference:
```
[LameXP.2188]
…
Flags\EnableSounds=false
```

File is usually found at:
```
C:\Users\YOUR_NAME_HERE\AppData\Local\LoRd_MuldeR\LameXP - Audio Encoder Front-End\config.ini
```

**Comment by Meguido** [comment]
Hey, looks like it's working now.
Adding this:
```
[LameXP.2188]
…
Flags\EnableSounds=false
```
to the config.ini file seem to do the trick. It's now working with no problem!

Thank you so much for your help 😊

I don't know if I should close it as fixed or if you'll need more info, now that's fixed. 
Let me know, please.

**Comment by lordmulder** [comment]
It's not really "fixed", we just found a workaround – disable all sound effects.

I have no idea why playing sounds causes a crash on your system. LameXP just uses standard `PlaySound()` system function to play sounds. And you are the first one to report any issues with that. So I'm going to assume there is some sort of issue with your system, such as a broken sound driver or whatever...

**Comment by Tyrben** [comment]
Same sort of error message here.

The direct cause is the impossibility to lock "lxp_curl.exe".

The indirect cause is my sysadmin blocking some sort of actions for security.

> GURU MEDITATION
> At least one of the required tools could not be initialized:
> File 'lxp_curl.exe' could not be locked!

**Comment by lordmulder** [comment]
> Same sort of error message here.
> 
> The direct cause is the impossibility to lock "lxp_curl.exe".
> 
> The indirect cause is my sysadmin blocking some sort of actions for security.
> 
> > GURU MEDITATION
> > At least one of the required tools could not be initialized:
> > File 'lxp_curl.exe' could not be locked!

No, I think this is an entirely different problem.

It means that LameXP was _not_ able to re-open a required file after it has been extracted.

This kind of issue is almost always caused by buggy "antivirus" software.

I have already implemented workarounds for this problem, so that LameXP will retry (several times) after a short delay, if the file couldn't be opened at the first attempt. But, at some point, we will ultimately have to give up and abort the program.

Try to disable/uninstall the "antivirus" software, or at least create an exception rule...

Regards.
