### ISSUE TITLE
Album Artist will be blank when converting with Lame XP

### ISSUE THREAD

**Issue by Cibomatto2002** [lordmulder/LameXP#118]
I already have it filled out but Lame XP shows it blank when converting. Could you guys add Album Artist to the meta data? 

![Capture1-27-2024-9 49 21 AM](https://github.com/lordmulder/LameXP/assets/21169038/a76816cb-7863-4432-a582-a9264cb8626f)

**Comment by lordmulder** [comment]
Tags you fill in on the "Meta Data" tab takes precedence over meta tags from the original/input file.

If you leave this just blank, it will take meta tags from the original/input file.

Go to the "Source Files" tab and click "Show Details" to see what has been detected from the original/input file(s).

**Comment by lordmulder** [comment]
If this MP3 is your original/input file then, then the "Title", the "Artis"t and the "Album" name have been detected correctly by LameXP (MediaInfo).

There appears to be **no** "Genre" or "Year" tags in the original/input file, which is confirmed by Mp3tag.

**Comment by Cibomatto2002** [comment]
I never fill out Genre or Year that's why its empty. I will get the encoder log Later today I'm at work right now.  If you would recode a song with lame xp then open it with mp3 tag you would see the Album Artist is empty I use mp3 tab to put in the missing info on the Album Artist I'm on windows 11 if that helps.

**Comment by lordmulder** [comment]
Sorry, you "problem" is not clear to me.

Again: LameXP will only re-embed meta tags into the **output** file that have already been present in the original **input** file. That plus whatever you have entered _manually_ on the "Meta Data" tab.

According to your sreenshots, your original **input** file only contains "Title", "Album" and "Artist" tags. Consequently those tags (plus whatever you have entered _manually_ on the "Meta Data" tab) are the only tags that you can expect in the generated *output** file.

**Comment by Cibomatto2002** [comment]
The problem I have is lame xp will not fill in the Album Artist it just fills in Artist the mp3tag picture I uploaded I filled it in already.

**Comment by lordmulder** [comment]
Sorry, the meta data model used by LameXP does **not** destinguish between "Artist" and "Album Artist".

**Comment by Cibomatto2002** [comment]
Thanks for your time. Sorry I was not plane enough. I'm not really good at telling people about things.
