### ISSUE TITLE
Filter System

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#12]
I've a great idea which can unburden user of manual filtering one's library: filters!

I have a large library, mostly lossless, but some of the files are mp3 or wav. When I'm converting the entire library, I set different options for different files to retain the same quality. Also, they are in different genre, some of them don't need high quality, some of them sound like crap in low bitrate.

For example, I'd like to convert genre "Rock" into m4a with moderate quality, meanwhile "Ambient" with the highest quality and skip the entire wav format, since I don't want to listen to it on my phone.

Here, the design of my idea:

![idea](https://cloud.githubusercontent.com/assets/9303235/7316123/0f31cdc6-ea96-11e4-98b5-5e1111727756.png)

I don't pretend to keep this UI; it's just my view on the filters.

P.S. It's not a bug, so I would post it on the forum, but after I registered, I got: "You are not allowed to post or reply until you have been registered for at least 5 days," so I posted it here.

**Comment by lordmulder** [comment]
This kind of *conditional filtering* system would certainly be "nice to have", but it would be a tremendous amount of work to implement. Therefore I can only say "patches welcome", but I cannot promise anything.
