### ISSUE TITLE
Is there a 64-bit version and/or a portable version?

### ISSUE THREAD

**Issue by DOSforever** [lordmulder/LameXP#121]
And it supports Windows from Windows XP 64-bit onwards?

**Comment by lordmulder** [comment]
The "main" (GUI) program is 32-Bit. There's **no** benefit (but a whole lot of work) in providing a 64-Bit version of the GUI.

The actual encoder/deocder binaries are provided in various versions, incldung "64-Bit" and "64-Bit + AVX2" versions:
https://github.com/lordmulder/LameXP/tree/master/res/tools

The GUI automatically selects the "best" encoder/deocder binary that is supported by the respective CPU it is running on, _at runtime_.

**Comment by DOSforever** [comment]
Thanks for the answer
