### ISSUE TITLE
Missing files in the file list

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#14]
I've just found an interesting bug: if I drop a directory that contains directories and an audio file(s), it skips the directories.

For example:
music_dir1/music_dir2
music_dir1/music_dir3
music_dir1/file.mp3

If I drop music_dir1, LameXP adds only file.mp3, skipping all the other directories.

How could it go unnoticed all these years?

**Comment by xtemp09** [comment]
It means that dropping folder and adding folder recursively are different functions since if I choose the recursive adding from the menu, it works fine.

It's just unexpected. =(

**Comment by lordmulder** [comment]
The Drag&Drop function is "smart" in the way that it does *not* add a dropped folder in a recursive fashion *by default*, but will decent into subdirectories if the dropped folder itself didn't contain any usable files. If you *explicitly* wish to recursively add an entire directory tree, you have to do it via ``File`` → ``Open folder recursively``.

**Comment by xtemp09** [comment]
Yes, I understood, I had a huge list of files skipped, that's why I added the issue. Didn't expected that.
