### ISSUE TITLE
Encoder_AAC_FDK.h missing

### ISSUE THREAD

**Issue by Buzzroid** [lordmulder/LameXP#15]
Hi,

I've failed to build due to missing Encoder_AAC_FDK.h in the source tree.

Thanks.

James

**Comment by lordmulder** [comment]
Sorry, seems like I overlooked these files in 99b68fcccbd2cff751fa5a0ab62e0597bf49140a, should be fixed in b78a4708785b66d393c638427bb8cc3573f91bd5.

**Comment by Buzzroid** [comment]
Thanks for the fix.

As a professional programmer, I've taken a deep look at your code.
The LameXP architecture and your coding skill is superb.
I've learn a lot.
Thank you very much for openning such a good software.

James

[PS] In the codes, there are some preparations for the CDDA files.
Do you plan to support those anytime soon?

**Comment by lordmulder** [comment]
Thanks.

Some info on CDA files: CDA files are "virtual" files, generated by Microsoft Windows. In fact, an Audio-CD does **not** contain any files, as it does **not** contain a *Data* track, only *Audio* tracks". The latter do **not** contain a file system (and thus no files), just the "raw" audio data. The CDA files that Microsoft Windows shows for an Audio-CD are just "dummy" files, 44 Bytes in size, that do **not** contain the actual audio data (PCM data). It's more a *link* or *pointer* to the actual audio track.

So, if you want the actual *Audio* data from the Audio-CD, you must "rip" the audio track. This is **not** as simple as reading or copying a file. If some read error occurs, the drive doesn't report read error, but instead returns possibly corrupted data (audio track is intended for *real-time* playback, **not** bit accurate copying). Also seeking in in audio track is not accurate, so you'll have to read *overlapping* blocks and "synchronize" the boundaries. All this is not trivial and I don't want to re-invent the wheel. So I suggest using EAC in "Read Image" mode. The CUE Sheet can then be imported in LameXP easily. That's what I do.

**Comment by Buzzroid** [comment]
Now I'm clear on the CDA files.

Regards,

2015-05-02 19:34 GMT+09:00 LoRd_MuldeR <notifications@github.com>:
