### ISSUE TITLE
Advanced rename pattern

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#16]
Could you extend features of rename pattern in "Advanced Options" with capability to replace output extension?
I need something like "\<Ext\>=m4a" to set the output extension to m4a.

I hope your urges to stick to the standards will let you do such a small thing. =)

**Comment by lordmulder** [comment]
I will look into a solution for this. However, replacing the file extension is inherently dangerous. Imagine you set it to "m4a" because you encode to MP4 today, but tomorrow you encode to Vorbis and forget to revert the file extension...

**Comment by xtemp09** [comment]
Simple warning when encoding (recheck/clean up on start) will avoid the problem. People usually convert into one and only format, if people use renaming they are aware of it.

Also, it will be helpful with opus. My phone doesn't understand .opus but plays it if file was renamed into .ogg.

**Comment by lordmulder** [comment]
> Also, it will be helpful with opus. My phone doesn't understand .opus but plays it if file was renamed into .ogg.

Now that's really weird! Yes, Opus streams are usually stored in Ogg container. But the file extension ``.ogg`` has been used synonymously with *Vorbis* for a long time. Most people even don't know the difference between *Ogg* and *Vorbis*. That probably is the reason why [*OggOpus*](https://wiki.xiph.org/OggOpus), i.e. the standard for Ogg-encapsulation of Opus streams, clearly says that ``.opus`` is the recommended extension.

**Comment by xtemp09** [comment]
Thanks, RegExp could be good too. I don't find the behavior of my player weird, since codecs and containers are usually disconnected, so that players could play any data wrapped by any container. It just doesn't really know .opus extension.

File outputs for both .ogg and .opus:
	$ file *
08 - Trash Palace - Venus In Furs.ogg:  Ogg data, Vorbis audio, stereo, 44100 Hz, ~160000 bps
08 - Trash Palace - Venus In Furs.opus: Ogg data
	$ file -i *
08 - Trash Palace - Venus In Furs.ogg:  application/ogg; charset=binary
08 - Trash Palace - Venus In Furs.opus: application/ogg; charset=binary

**Comment by lordmulder** [comment]
Yes, I know that the *container* format (e.g. Ogg, MKV or MP4) and the *audio* format (Opus, Vorbis, AAC, etc). are two separate things. But there is **nothing** in the Ogg specifications that says that all Ogg files *must* have a file name that ends in ``.ogg``. Actually, the Ogg specification discourages using ``.ogg`` in favor of ``.ogx``. That'S because "historically, some implementations expect .ogg files to be solely Vorbis-encoded audio". Also, the Ogg specification *does* define that every Ogg file starts with the **magic bytes** ``0x4f``, ``0x67``, ``0x67`` and ``0x53`` (correspond to the string "OggS"), so that's what application should check for - instead of making vague assumptions based on the file name! Furthermore, the [*OggOpus*](https://wiki.xiph.org/OggOpus) specification, which defined the Ogg-encapsulation for Opus streams, clearly recommends using ``.opus`` file extension for "Opus in Ogg" files.

**Comment by lordmulder** [comment]
> Thanks, RegExp could be good too.

Some initial work has been on the enhanced renaming support has been done:
effb417eb5d5f729e3b2f3161dcdbcfd9d39543b

**Comment by lordmulder** [comment]
Okay, enhanced file renaming options should be done now:
a70919dcbef8a0379b8cd4ce0a94d9fda249300e

**New Test-Build:**
https://www.sendspace.com/file/93kxfo

**Comment by xtemp09** [comment]
Everything works just fine. Happy to have the library converted without additional renaming software. =))

 I ought to say that one thing works unexpectedly - qaac.

One of the threads I created here contains my remark about incompatibility with qaac64. You told me that simple renaming qaac64 qaac will make it work. But your program checks the presence of qaac with libsoxr.dll and libsoxconvolver.dll.

If I rename qaac64.exe qaac.exe, LameXP completely skips the QAAC encoder. I have to copy libsoxr64.dll into libsoxr.dll so as libsoxconvolver64.dll into libsoxconvolver.dll to make it work and be seen by LameXP.

Could you add check for qaac64 libraries?

**Comment by lordmulder** [comment]
> One of the threads I created here contains my remark about incompatibility with qaac64. You told me that simple renaming qaac64 qaac will make it work. But your program checks the presence of qaac with libsoxr.dll and libsoxconvolver.dll.
>If I rename qaac64.exe qaac.exe, LameXP completely skips the QAAC encoder. I have to copy libsoxr64.dll into libsoxr.dll so as libsoxconvolver64.dll into libsoxconvolver.dll to make it work and be seen by LameXP.

When I said this, I was assuming that 64-Bit QAAC uses a different *executable* name, but its companion DLL's still have the same names. If that isn't the case, then just renaming the EXE won't work, yes.

> Could you add check for qaac64 libraries?

Well, I could. But before I add this additional complexity, I first need to know why you want to use 64-Bit version. And please don't tell me "I have a 64-Bit system, so everything must be 64-Bit now". The primary difference between 32-Bit and 64-Bit mode is that 64-Bit mode uses wider addresses and thus can address more memory. For some applications being able to address more than 4 GB of memory can be a huge improvement – for QAAC it is *not* relevant though. It is also possible that the 64-Bit version runs slightly faster than 32-Bit version. But did you actually verify this with a proper test ???

**Comment by xtemp09** [comment]
I just compared time needed to convert an audio file and a directory of audio files.

Instance | 64-bit | 32-bit
----- | --- | ---
1 file: |     10.697 s   |  13.011 s
13 files: |    70 s	|	85 s

2 instances, Phenom X3 2.8 GHz, OCZ SSD.

As we see, there is a constant gain in speed.

Do I need to videotape this in the presence of notary? =)

Thanks again for implementing advanced renaming. Now I have one less problem when converting my library.

**Comment by lordmulder** [comment]
> Do I need to videotape this in the presence of notary? =)

Nope. If you can confirm that the 64-Bit version indeed runs notably faster that the 32-Bit version on your system, I will believe you. I just wanted to be sure that we don't add this for no good reason.

**Try this build:**
https://www.sendspace.com/file/3vuah2

**Comment by xtemp09** [comment]
Everything seems to be working as expected, thanks.
