### ISSUE TITLE
Multiple selection in Source tab

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#18]
Sometimes, after I add an artist in the source list (~60 songs), I need to delete some songs (13-20 songs). It causes discomfort since I have to select and delete every item one-by-one.

The program freezes for a second after every deletion, which also doesn't help.

Could you add multiple selection in the source list?

**Comment by lordmulder** [comment]
Maybe selecting multiple elements could be enabled. But it makes many things more complex, especially when it comes to *moving* the "current item" up or down.

**Comment by xtemp09** [comment]
Maybe, this link will help:

http://stackoverflow.com/questions/4031168/qtableview-is-extremely-slow-even-for-only-3000-rows

**Comment by lordmulder** [comment]
> Maybe, this link will help:
> http://stackoverflow.com/questions/4031168/qtableview-is-extremely-slow-even-for-only-3000-rows

This Stackoverflow post just confirms that updating the View can become pretty "slow" when the Model contains a lot of items. The "workaround" that is suggested – add *all* items to the Model **before** connecting the View to the Model – only avoids that the View will be updated instantly for every single item that we add. Instead, the View will be updated only *once*, after all items have been added. And, indeed, I have implemented the same "optimization" in LameXP for a long time! As you may have noticed, when you are adding a large number of files in LameXP, then the View will **not** be updated instantly for every file that is added. Instead, the View is updated *once* at the end, after all files have been added.

BUT: If you delete a *single* item from the list, there is **no** way to "optimize" the View update! We are applying exactly one modification to the Model – we remove a single file at a time – and after that modification the View needs to be updated.

**Comment by lordmulder** [comment]
> Could you add multiple selection in the source list?

Here is a new **test build** with *experimental* multi-file selection:
https://www.sendspace.com/file/85defj

----------------

> Maybe, this link will help:
> http://stackoverflow.com/questions/4031168/qtableview-is-extremely-slow-even-for-only-3000-rows

This Stackoverflow post just confirms that updating the View can become pretty "slow" when the Model contains a lot of items. The "workaround" that is suggested – add *all* items to the Model **before** connecting the View to the Model – only avoids that the View will be updated instantly for every single item that we add. Instead, the View will be updated only *once*, after all items have been added. And, indeed, I have implemented the same "optimization" in LameXP for a long time! As you may have noticed, when you are adding a large number of files in LameXP, then the View will **not** be updated instantly for every file that is added. Instead, the View is updated *once* at the end, after all files have been added.

BUT: If you delete a *single* item from the list, there is **no** way to "optimize" the View update in this way! We are applying exactly one modification to the Model – we remove a single file at a time – and after that modification the View unavoidably needs to be updated. So **no**, it doesn't help here, unfortunately...

**Comment by lordmulder** [comment]
Nobody has complained, so far. So I'll considered that one done.
