### ISSUE TITLE
Skipping images and ini-files

### ISSUE THREAD

**Issue by xtemp09** [lordmulder/LameXP#19]
When one adds a directory, the program recursively searches for files, adding only those ones that are supported, skipping other files.

Could you add statistics for that? For example, if the program skips image file (JPEG or PNG) in the end Lame XP says something like: "6 images skipped." Some directories contain Desktop.ini or Thumb.db. I suggest skipping them and adding to the statistics as well.

I imagine the final Message Box saying the following: "60 media files have been added. 7 image files and 7 thumbnail files have been skipped."

I think that it will be more informative than just "14 files have been skipped."

**Comment by lordmulder** [comment]
This is *not* really feasible. LameXP doesn't know (and doesn't *need* to know) anything about, e.g., "image" or "thumbnail" files. Either a file is a supported audio file type, as detected by MediaInfo, or it is an *unknown* file, which LameXP cannot handle and which therefore has to be skipped.
