### ISSUE TITLE
If Beta Update Check confirms I have the latest version...

### ISSUE THREAD

**Issue by MisterZeus** [lordmulder/LameXP#25]
...the update checker should extend the Binary's Expiration Date by a month or something.
Right now, everyone who was using a Beta version cannot use it anymore and has to revert back to the main branch from April 2015!

**Comment by lordmulder** [comment]
There usually should be a new Beta build, before the previous one expires. Anyway, the Beta builds are intended for testing, not for long-term use. A new build is up now.
