### ISSUE TITLE
wav conversion to ogg: sample rate problem

### ISSUE THREAD

**Issue by foggyxp** [lordmulder/LameXP#26]
Conversion of a wav-file of a cd-ripping 44.1 kHz to an ogg-file with a sample rate of 32 kHz doesn't work; only conversion to 44.1 kHz is possible.
(LameXP v4.11 and v4.12,  windows 7 pro).  As much as i remember it worked before.
On mobile players 32 kHz-files (mp3 and ogg) sound much better than 44.1 kHz. That's why i need to downsample.
(conversion to mp3 there is no problem with any sample rate)

**Comment by lordmulder** [comment]
There seems to be a bug in **OggEnc2** regarding *resampling*. I just noticed that a newer version of *OggEnc2* is available now, which claims to have fixed the "resampling bug". I will update *OggEnc2* soon.

BTW: According to *Nyquist–Shannon sampling theorem*, the max. frequency that can be retained is 1/2 the sampling rate. So by going down from a sampling rate of 44.1 kHz to a sampling rate of 32 kHz, you are effectively *low-pass* filtering the signal. In other words, you are throwing away the highest frequencies.

**Comment by lordmulder** [comment]
Okay, please tray with this **test** build:
http://sourceforge.net/projects/muldersoft/files/LameXP/Testing/LameXP-TEST.2015-10-26.Release.Build-1825.7z/download

**Comment by foggyxp** [comment]
Thank you
2015-10-26.Release.Build-1825.7z:  resampling to 32 kHz  ogg-file works well. While the programm is runnig, the LameXP Debug Console-Window stays open.

**Comment by xtemp09** [comment]
Why do developers not use g++ when linking it against Qt?

I just realized if it were compilable with g++, people would download it and compile it easily, since there are a lot of small gcc bundles and building environments, instead of downloading the entire Visual Studio.

**Comment by lordmulder** [comment]
LameXP is developed in Visual Studio (Visual C++), so cannot link it again the MinGW version of Qt. Mixing pure C code from different compiles is possible to a certain degree, but mixing C++ code from different C++ compiles is **not** possible. Heck, if you want to use  the "official" MinGW builds of MinGW you even have to use the exactly same MinGW version/flavor that the Qt guys used to make their binaries.

**Comment by xtemp09** [comment]
I meant those ones that are listed in "[Downloads](http://www.qt.io/download-open-source/)" on qt-project.

Qt is bundled with Qt Creator+gcc. When I was creating screenshots in one of the issues, I opened the project in Qt Creator and even compiled it, but it required manual involvement in compilation process and code analysis.

**Comment by lordmulder** [comment]
If you want to link LameXP with the "official" *pre-compiled* Qt libraries for **MinGW**, then you have to build the *entire* application (which also includes all third-party libraries!) with MinGW/GCC! Currently, LameXP is built using Visual Studio, so we would have to switch the *build system* from a Visual Studio Project (MSBuild) to either a Qt Creator Project or a GNU Makefile. And that not only for LameXP itself, but also for all third-party libraries. That alone would be a big amount of work! But, as experience shows, C/C++ code written for Visual Studio won't compile under MinGW/GCC without additional tweaks and hacks. And if you which to maintain compatibility with both, MinGW/GCC *and* MSVC, your code will be cluttered with `#ifdef` hackery...
