### ISSUE TITLE
Missing tags when converting to AAC using fhgaac codec

### ISSUE THREAD

**Issue by georgefl** [lordmulder/LameXP#40]
I am using LameXP Version 4.13 Final-1, Build 1852 to convert from FLAC to AAC using fhgaac v03.02.16 and no tags are transferred.
If I convert to AAC with foobar2000 (using fhgaac v03.02.16) all the tags are transferred.

**Comment by lordmulder** [comment]
_fhgaac_ does **not** support embedding meta tags. I'm referring to the CLI fornt-end (by tmkk) here, which is used by LameXP.
