### ISSUE TITLE
Not recognizing Nero encoders

### ISSUE THREAD

**Issue by secretclean** [lordmulder/LameXP#41]
I've used LameXP countless times this year, but several days ago I updated to the most recent build. The next time I started the program, I got the error that "Nero AAC encoders could not be found." I didn't change anything, and when I checked the folder they were still there.

I uninstalled and reinstalled the program, and extracted the NeroAAC 1.5.1 exes over again, but I'm still having this issue. I'm on Windows 10, 64-bit. What's going wrong here?

![medcnar](https://cloud.githubusercontent.com/assets/16670517/18727183/8860ce70-8015-11e6-9e69-0c142cfd341e.png)

**Comment by lordmulder** [comment]
Run `LameXP.exe` with parameter `--console` to get more info, i.e. type this in a terminal:

    "c:\Path to LameXP\LameXP.exe" --console

-------

Also version 1.5.**4**.0 should be used! Go get it here, as the Nero web-site has a wrong ZIP file:
http://www.videohelp.com/software/Nero-AAC-Codec

**Comment by lordmulder** [comment]
No more reply in two weeks, so I'm going to assume the issue has been resolved.
