### ISSUE TITLE
mp3 Sample Rate Problem (VBR Q8 - 44kHz)

### ISSUE THREAD

**Issue by foggyxp** [lordmulder/LameXP#48]
LameXP version 4.14 Final-1, Build 1934
Windows 7  64bit  Prof 
Original mp3-File is:  128kbps   44,1kHz   STEREO,  File Size: 2'947'030 Bytes

---------
Setting in LameXP:
-- Compression: VBR, Quality Level 8
a) -- Advanced Options: Sampling Rate Hz 48.000  /  MP3 Channel Mode: Mono
a) The Output is: Sampling Rate Hz 48.000  mono   File Size: 943'104 Bytes
---------
Setting in LameXP:
-- Compression: VBR, Quality Level 8
b) -- Advanced Options: Sampling Rate Hz 44.100  /  MP3 Channel Mode: Mono
b) The Output is: Sampling Rate Hz 24.000  mono   File Size: 942'312 Bytes
---------
Setting in LameXP:
-- Compression: VBR, Quality Level 8
c) -- Advanced Options: Sampling Rate Hz 32.000  /  MP3 Channel Mode: Mono
c) The Output is: Sampling Rate Hz 32.000  mono   File Size: 825'984 Bytes
---------
Setting in LameXP:
-- Compression: VBR, Quality Level 8
d) -- Advanced Options: Sampling Rate Hz 24.000  /  MP3 Channel Mode: Mono
d) The Output is: Sampling Rate Hz 24.000  mono   File Size: 709'800 Bytes
---------

Question:
 What happens here? 
Why is the Output in b) only 24 kHz instead of 44 kHz?  (Setting 44 kHz!)
Why is the Output in d) also 24 kHz (Setting only 24 kHz!) but the filesize is much smaller?
Why is with this Setting (Compression: VBR, Quality Level 8)  no Output with 44 kHz possible?

Thank you for any good explanation (I am not an expert..)

**Comment by foggyxp** [comment]
the older version LameXP version 4.12  Build 1818    (with the same setting, see above)   does not reduce the original Sampling Rate of 44 kHz to 24 kHz in the output.

**Comment by lordmulder** [comment]
The LAME mp3 encoder _automatically_ reduces the sampling rate at those **ultra-low** bitrates. Reduicng the sampling rate effectively works like a "low-pass" filter, according to [_Nyquists-Shannon Theorem_](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem), i.e. it means that the highest frequencies are "discarded". The LAME developers have heavily tuned their Psy models and, obviously, at those **ultra-low** bitrates, down-sampling to 24 kHz is the better _trade-off_ - compared to the compression artifacts that you'd get when trying to retain the "full" 44.1 kHz frequency range.

**See also:**
https://hydrogenaud.io/index.php/topic,53573.0.html
