### ISSUE TITLE
 Optional FFMPEG Decoding

### ISSUE THREAD

**Issue by BiatuAutMiahn** [lordmulder/LameXP#52]
Can you implement an option to allow ffmpeg to decode the input file? FFMPEG is large, but it is able to handle decoding much better than the current method. For example, I have a collection of aac stream that I pulled straight from a server, but LameXP's decoder chokes on them cause they're in a messed up format, ffmpeg however still converts them to a wave. Another benefit with using ffmpeg would be to do some of the filtering, downmixing...etc on the fly, and then pipe the stream straight to an encoder instead of using loads of space for a wav.

Just a thought, what do you think?

**Comment by DajMiliona** [comment]
2 years...
I am waiting too for FFMPEG

**Comment by lordmulder** [comment]
Patches welcome 😏 

Otherwise it is probably not happening anytime soon, due to lack of time and enthusiasm.

Regards.
