### ISSUE TITLE
question: Can Opus also be encoded to more than 256 kbps?

### ISSUE THREAD

**Issue by Sa-Ja-Di** [lordmulder/LameXP#54]
People wrote that the max capacity is around 512? Can i use some command line parameters for this or does this method so far not work in LameXP?

Anyway, great program :)

**Comment by lordmulder** [comment]
Hello.

Allowed Opus bitrate is 6 to 256 kpps, **_per channel_**:
https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html#--bitrate

**Comment by lordmulder** [comment]
Hello,

allowed Opus bitrate is 6 to 256 kpps, **_per channel_**:
https://mf4.xiph.org/jenkins/view/opus/job/opus-tools/ws/man/opusenc.html#--bitrate

So, yes, if we encode _Stereo_ source, we can use up to 512 kbps, in theory. But does it really make sense ❓

Opus compression for **music** (stereophonic source sampled at CD quality) is said to be _"very close to transparent"_ at 96 kbps to 128 kbps, and _"transparent (with very low chance of artifacts)"_ at 192 kbps:
http://wiki.hydrogenaud.io/index.php?title=Opus#Music_encoding_quality

**Comment by lordmulder** [comment]
Think we can close this one,
