### ISSUE TITLE
How do I select between LC-AAC and HE-AAC, or...

### ISSUE THREAD

**Issue by Starlite528** [lordmulder/LameXP#55]
Or what profile does the Nero AAC encoder use?  I'm trying to re-convert some AAC audio files that for some reason my car radio is not accepting.

**Comment by lordmulder** [comment]
Hi.

You can enforce a specific AAC profile on the "Advanced Options" page. 
But it is recommended to keep the default, i.e. let Nero AAC decide 
automatically based on the target bitrate. HE-AAC (or even HE-AACv2) 
generally is only advantageous at very low bitrates. It is actually 
detrimental for the higher bitrates! So let the encoder decided what to use.

Best Regards,
MuldeR


BTW: HE-AAC(v2) is fully backwards-compatible to LC-AAC. HE-AAC is just 
LC-AAC+SBR. Decoders that don't know about HE-AAC (SBR) will decode it 
as normal LC-AAC.
