### ISSUE TITLE
Music library volume normalization?

### ISSUE THREAD

**Issue by markreg** [lordmulder/LameXP#56]
Hello, I'm trying to normalize a large library of songs, instrumentals of different genres so that I do not have to adjust the volume as frequently on my amplifier. Currently all the files are OPUS files being played by Music Player Daemon on a raspberry pi.

Is it possible to normalize these files to some RMS value across all files using LameXP with minimal or no quality degradation? Something similar to ReplayGain but for OPUS files (re-encoding is ok)? And would the entire library need to be re-encoded once another file has been added or can I select some arbitrary dB value to normalize new audio files to?

Sorry if I'm not as clear in the description of what I want to achieve, I'm a bit new to this side of audio. Thanks.

**Comment by lordmulder** [comment]
AFAIK, the volume of Opus files can't be changed _without_ full re-encoding.

ReplayGain should work, as it does **not** actually modify the audio file, but instead only adds a meta information to the audio file and then relies on the playback software to actually adjust the volume...

Regards,
MuldeR

**Comment by markreg** [comment]
@lordmulder 

I actually still have the original wave files that were used to convert to OPUS so I can use those Essentially my goal is to re-encode all the files, which are are from about 10 different albums, and alter the average volume of all files to around the same value. I'm not sure which tool can best accomplish this since ReplayGain only adds a meta tag as you mentioned. I'd like the volume solution to be player agnostic in any case since I have a few different devices that the collection is played on.
