### ISSUE TITLE
PCM-wav (16bit stereo, 44.1 kHz, direct CD rip) wrongly identified as DTS

### ISSUE THREAD

**Issue by pupvogel** [lordmulder/LameXP#57]
Hi,
I have a ripped wav-file here, which converted to a .flac-file without error - but empty.
Looks like LameXP identifies the file as DTS-encoded, even though it isn't, then somehow conversion goes through without error.
At least WinAmp reports correct wav-encoding (44.100, 16bit PCM).
When converting the file with flac command-line-tool, I get a correct .flac-file.
https://drive.google.com/file/d/1DoTpV_3HgVSJdIfoLROXqfgnAwMS2dXr/view?usp=sharing

**Comment by pupvogel** [comment]
Looks like this is a MediaInfo-issue - posted it over there, too.

**Comment by lordmulder** [comment]
Okay, thanks.
