### ISSUE TITLE
Vorbis decoding

### ISSUE THREAD

**Issue by Envergure** [lordmulder/LameXP#59]
Hello, 

This is a feature request.  I am trying to convert a collection of drum samples and sound effects that are Vorbis encoded but in a .wav container.  I am basically downloading all the audio converters I can find until one works lol.  In LameXP, the files fail to convert because the input CODEC is not supported.

An example file that failed to convert is attached.  Change the extension back to .wav before opening, because GitHub only allows certain extensions for attachments!

(FYI, VLC says this file is MP3, not Vorbis, but VLC can't play the file so I am assuming Vorbis is correct.)

![hit_1](https://user-images.githubusercontent.com/14314362/33938734-8d9713fa-dfd6-11e7-82a0-643c215e295e.jpg)

Regards, 
Chris

**Comment by lordmulder** [comment]
Hello.

Please download **MediaInfo** from here:
https://sourceforge.net/projects/muldersoft/files/MediaInfo%20%28CLI%2BGUI%29/MediaInfo-CLI.2017-11-05.zip/download

Then run this command from the Terminal:
MediaInfo.exe --output=xml "c:\path\to\your\input.wav" > output.xml

Then please send me the resulting "output.xml" file.

Regards,
MuldeR

**Comment by Envergure** [comment]
Here is the XML file.
[output.xml.txt](https://github.com/lordmulder/LameXP/files/1557611/output.xml.txt)

Just to add: These audio files all do open and play in Audacity and in FL Studio.  They aren't corrupt or anything like that.

**Comment by lordmulder** [comment]
So, this is really Vorbis stream wrapped in WAV container.

This is **very** unusual, as the "native" container for Vorbis is Ogg, It's commonly called Ogg/Vorbis.

What software was used to create this? :question:

I have been able to create such a file with _FFmpeg_, by adding `-c:a libvorbis` and `-f wav` options.

However **_nothing_** is able to play this. Neither MPlayer, nor VLC Player, nor MPC-HC :angry:

Also, _OggDec_, which is the Vorbis decoder used by LameXP, doesn't recognize the file either:

    >oggdec.exe -w out.wav e:\vorbis.wav

    OggDec v1.10.1 (libVorbis 1.3.5) Compiled on: Mar 19 2015
    Input e:\vorbis.wav does not appear to be an Ogg bitstream.
    ********** Done decoding all input files. **********

Not even _FFmpeg_ will read the file that it created itself:

    >ffmpeg.exe -i e:\vorbis.wav e:\out.wav
    
    ffmpeg version N-85469-gf1d80bc Copyright (c) 2000-2017 the FFmpeg developers
    Press [q] to stop, [?] for help
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.
    Error while decoding stream #0:0: Invalid data found when processing input
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.
    Error while decoding stream #0:0: Invalid data found when processing input
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.peed=0.0328x
    Error while decoding stream #0:0: Invalid data found when processing input
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.
    Error while decoding stream #0:0: Invalid data found when processing input
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.
    Error while decoding stream #0:0: Invalid data found when processing input
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.
    Error while decoding stream #0:0: Invalid data found when processing input
    [vorbis @ 00000000046a5f80] Not a Vorbis I audio packet.
    Error while decoding stream #0:0: Invalid data found when processing input
    ... and so on ...

Looks like a lost case to me...

Regards,
MuldeR
