### ISSUE TITLE
Checking {no re-sampling} in opus format still resamples.

### ISSUE THREAD

**Issue by tejasvi8874** [lordmulder/LameXP#62]
For e.g. 44.1kHz FLAC -> Opus ( output to 48 HZ checked ) still produces 44.1kHz Opus file.

**Comment by lordmulder** [comment]
Opus is a "48 KHz only" format. Anything _not_ already at 48 KHz will be re-sampled to 48 KHz.

Actually the re-sampling happens in the Opus CLI front-end, as the actual Opus _**encoder**_ library only takes 48 KHz signals as input. There is **no** way around this!

However, Opus remembers the "original" sampling rate, so the Opus _**decoder**_ can re-sample back to the "original" sampling rate - which it does by default. 

The option you are referring to makes the Opus _**decoder**_ output the 48 KHz.

**Comment by tejasvi8874** [comment]
That's what I'm saying. It always outputs original frequency irrespective of ticking the option (i.e. in both cases). It works fine in stable version.

**Comment by lordmulder** [comment]
Should be fixed in 6ae5295cf13c4630d90105eb2e800348b95508af. Please try new TEST build:
[**LameXP-BETA.2018-03-17.Release-Static.Build-2104.exe**](https://sourceforge.net/projects/muldersoft/files/LameXP/Testing/LameXP-BETA.2018-03-17.Release-Static.Build-2104.exe/download)

MuldeR.
