### ISSUE TITLE
MediaInfo is crashing after upgrading to 4.16 RC3+

### ISSUE THREAD

**Issue by przemas2468** [lordmulder/LameXP#65]
When I add a sound file *.flac with a cover, it pops up a window with the interruption of the MediaInfo process. In the <RC2 version there was no problem, but after the most recent update to RC4 it still exists. I attach screenshots and log to this error.

![Screenshot 1](https://user-images.githubusercontent.com/4410892/38929852-05739ad4-430e-11e8-80bd-af56577e8480.png)
![Screenshot 2](https://user-images.githubusercontent.com/4410892/38929853-059a2bb8-430e-11e8-9b71-4b30bc025152.png)
[**Log.txt**](https://github.com/lordmulder/LameXP/files/1923819/Log.txt)

**Comment by lordmulder** [comment]
Hello.

Does it happen with any audio files? Or only with FLAC? Or only with this specific FLAC file?

You can try with my [**MediaInfo** builds](https://sourceforge.net/projects/muldersoft/files/MediaInfo%20%28CLI%2BGUI%29/MediaInfo-CLI.2018-04-13.zip/download) directly from the command-line:
```
mediainfo.exe --Language=raw --Full --Output=XML --Cover_Data=base64 <audio_file>
```

If this only happens with a specific file, can you please provide an example file?

Regards
MuldeR

**Comment by lordmulder** [comment]
See here please:
https://github.com/MediaArea/MediaInfo/issues/227

**Comment by lordmulder** [comment]
Bug has been fixed in MediaInfo. Will update to latest MediaInfo soon...

**Comment by przemas2468** [comment]
OK, it looks like this problem has been solved. Very thanks for the releasing fix. :wink:
