### ISSUE TITLE
conversion from opus audiobooks to ogg yields a truncated ogg

### ISSUE THREAD

**Issue by pweasel** [lordmulder/LameXP#66]
Hi there, I have a bunch of 20+ hrs opus audiobooks i tried to convert to ogg (my player doesn't support straight opus) and all of them end up with 6:12:48 of converted audio.

**Comment by lordmulder** [comment]
Hello.

Even if you convert from Opus to Ogg/Vorbis, what happens "behind the curtain" is that your orginal Opus file is *decompressed* to Wave Audio via OpusDec first, and then the temporary Wave Audio file is *compressed* to Ogg/Vorbis. Now, unfortunately, the Wave Audio file format uses **32-Bit** size fields all the way – which means that Wave Audio files *technically* can **not** grow larger than 4 GB of total size.

With extremely long files, such as audio books and stuff, you may run into that limitation. In that case, you file will be truncated at the 4 GB barrier. There is, unfortunately, not much I can do about this...

Regards
MuldeR
