### ISSUE TITLE
LameXP v4.16 [2018-04-30] now failing when converting

### ISSUE THREAD

**Issue by smileystv** [lordmulder/LameXP#67]
Hello,

I have no idea what changed, but I have been batch converting MP4s and all of them fail within milliseconds.

Nothing has changed on my end.  I was converting and then an update appeared and then everything failed thereafter.

I have installed and reinstalled... Same issue.

Any advice?

**Comment by smileystv** [comment]
A log file output:


LameXP v4.16 (Build #2134), compiled on 2018-04-30 at 14:48:13

-------------------------------

C:/Users/STEVEV~1/AppData/Local/Temp/813c3f6bdd675e0b/lxp_faad.exe -o C:\Users\XXXXX~1\AppData\Local\Temp\813c3f6bdd675e0b\01e2464ec9f6f3c4.wav "C:\Users\XXXXXXX\Desktop\New folder\Kacey Musgraves High Horse (Live).mp4"

*********** Ahead Software MPEG-4 AAC Decoder V2.8.6 ******************
Build: Dec 16 2017
Copyright 2002-2004: Ahead Software AG
http://www.audiocoding.com
bug tracking: https://sourceforge.net/p/faac/bugs/
Floating point version
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License.
**************************************************************************
**** MP4 header ****
Brand: isom(version 512)
Compatible brands: isomiso2avc1mp41
*track media type: 'vide': unsupported, skipping
*track media type: 'soun': OK
parse:-1
Error opening file: C:\Users\XXXXXX\Desktop\New folder\Kacey Musgraves High Horse (Live).mp4

Exited with code: 0x0000

**Comment by smileystv** [comment]
The file is 33MB and sent via Dropbox.

I have tried multiple files, all coming from YouTube... Maybe that's the deal.

I even changed the file name to "1" and it still doesn't work.

I reverted back to the previous version though and all is well no matter the naming?

Maybe its the metadata???  I have zero clue.

Thanks for looking into this.


________________________________

**Comment by lordmulder** [comment]
> The file is 33MB and sent via Dropbox.

Okay. Can you please send me the Dropbox link via e-mail then?

> I even changed the file name to "1" and it still doesn't work.

I don't think the file name is the problem (but yeah, you never know).

> I reverted back to the previous version though and all is well no matter the naming?

Well, I updated FAAD to latest version in thew new LameXP release. So, maybe, a regression in FAAD.

Regards.

**Comment by smileystv** [comment]
You are like... The Best.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smileystv** [comment]
Any resolution on this?
________________________________

**Comment by lordmulder** [comment]
Unfortunately, no. There was **no** reply from the FAAD developer to my report.

I probably will stick with FAAD v2.7 for the next release of LameXP, as in the latest Alpha release:
[**LameXP-ALPHA.2018-06-03.Release-Static.Build-2142.exe**](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2018-06-03/LameXP-ALPHA.2018-06-03.Release-Static.Build-2142.exe/download)

**Comment by lordmulder** [comment]
Should be fixed in [**LameXP v4.17 RC-4**](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2018-10-24/LameXP-RC4.2018-10-24.Release-Static.Build-2182.exe/download).
