### ISSUE TITLE
LameXP v4.16 does not convert WMA-Files 

### ISSUE THREAD

**Issue by foggyxp** [lordmulder/LameXP#68]
Version 4.16 ist the first one no more accepting wma-format.
(Installation-File:  LameXP.2018-04-30.Release-Static.Build-2134.exe)

I went back to v415 and there is no problem.
(Installation-File:  LameXP.2017-05-31.Release-Static.Build-2002)

**Comment by lordmulder** [comment]
Hello,

please see here:
https://forum.doom9.org/showpost.php?p=1842440&postcount=1537
