### ISSUE TITLE
20% of m4a files fail as "unsupported"

### ISSUE THREAD

**Issue by floatingshed** [lordmulder/LameXP#69]
The title says it all. I want to convert many m4a files to ogg but I'm getting a high failure rate. All my m4a's were created by nero with the same settings (afaik)!
Unfortunately I cannot attach examples of audio here.

**Comment by lordmulder** [comment]
Should be fixed in [**LameXP v4.17 RC-4**](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2018-10-24/LameXP-RC4.2018-10-24.Release-Static.Build-2182.exe/download).
