### ISSUE TITLE
Issue converting a specific FLAC version?

### ISSUE THREAD

**Issue by dfg555** [lordmulder/LameXP#75]
Seems like the program is having trouble converting this specific FLAC codec? I've worked with other FLAC files and they had no issue being converted to MP3 320Kbps CBR. I used Audacity instead to convert this file and it worked.

LameXP v4.16 (Build #2134), compiled on 2018-04-30 at 14:48:13

-------------------------------

The format of this file is NOT supported:
E:/My Downloads/MKAlieZ.flac

Container Format:	Commercial
Audio Format:	FLAC, Bitrate: ≈977 kbps (Variable), Encoder: reference libFLAC 1.2.1 20070917

----------------------------------
More info about the file:

Format                                   : Commercial
Format/Info                              : Free Lossless Audio Codec
File size                                : 25.9 MiB
Duration                                 : 3 min 42 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 978 kb/s

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 3 min 42 s
Bit rate mode                            : Variable
Bit rate                                 : 977 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 25.9 MiB (100%)
Writing library                          : libFLAC 1.2.1 (UTC 2007-09-17)

**Comment by lordmulder** [comment]
Hello.

Actually, there is **no** such thing as a "specific FLAC codec". There may be different software (or hardware) implementations that encode or decode audio data to/from FLAC format, but the FLAC format is always the same. There exists an "official" FLAC specification to which every implementation ***must*** adhere:
https://xiph.org/flac/format.html

LameXP uses the "official" FLAC encoder/decoder (libFLAC) from Xiph.org, latest "stable" version – which is the *reference* implementation of the FLAC format. So, if the "official" FLAC decoder won't decode a specific FLAC file, then the file in question is probably either invalid or broken in some kind of way.

Anyhow, there was a regression in the file format detection in last LameXP release. Did you try with current "RC" release?
https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2018-10-21/LameXP-RC3.2018-10-21.Release-Static.Build-2176.exe/download

Regards,
MuldeR

**Comment by lordmulder** [comment]
Did you try with latest "RC" release, now [**RC-4**](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2018-10-24/LameXP-RC4.2018-10-24.Release-Static.Build-2182.exe/download) ???

If you still have problem with this one, please provide a sample file!

Regards,
MuldeR
