### ISSUE TITLE
Files not being Overwrited (when ussing Same folder as the input)

### ISSUE THREAD

**Issue by jjpl2001** [lordmulder/LameXP#76]
Hello. When I select "Overwrite Existing File" under "Advanced Options" and I select "Save Files to the same location as input file" After encoding I still get a duplicated file.

I'm trying to reduce the size a complete MP3 discography well organized under folders, I wish that the program just overwrites the old bigger 320kbps MP3 files with the new 192kbps files, keepeing same name and metafile.

Thenks

**Comment by lordmulder** [comment]
Hello.

_Input_ and _output_ file for an encoding task can **not** be the same, for obvious reasons.

Regards.

**Comment by lordmulder** [comment]
> Sorry if I'm missing something, but as the output files are being directly written to a temp folder and then copied to the destination folder this shouldn't be an issue.

...a temporary file is generated if and only if the encoder cannot read the input format directly.
