### ISSUE TITLE
Keep configuration between updates

### ISSUE THREAD

**Issue by Svish** [lordmulder/LameXP#79]
When the program updates itself, all configuration seem to be reset. It's _super_ annoying. Especially the sound effects, and the advanced options. _Please_ leave my configuration _alone_ during the update procedure...

**Comment by lordmulder** [comment]
Configuration for different releases is stored *separately*, because configuration parameters may change their meaning between releases. But you can simply ***rename*** the sections in the config file, if you want to take the risk...
