### ISSUE TITLE
Opus 1.3.1 update is available

### ISSUE THREAD

**Issue by Sa-Ja-Di** [lordmulder/LameXP#80]
Any plans to update LameXP with the updated stable Opus codec version? :)

Opus 1.3.1 was released a while ago.

**Comment by lordmulder** [comment]
Hello, please see here:
https://github.com/lordmulder/LameXP/commit/c5eec833ba3020f8d71785dce094abf02f3872c3

You can get the latest "pre-release" builds here:
https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/2019-06-18/

Regards.
