### ISSUE TITLE
New stable release of LameXP soon??

### ISSUE THREAD

**Issue by expanse191** [lordmulder/LameXP#85]
Hello,
LameXP is such a great tool, thank you, I find it very useful.
Are you going to release a new stable version of it soon? I noticed it hasn't been updated in a long time. Could you include in a new release latest version of codecs like libopus, libvorbis, etc.???
Also, could the next version include AAC encoder by default, without having to download it ourselves please? Or at least, an automated way of downloading and installing it?

**Comment by lordmulder** [comment]
Hello.

Maybe there will be a new release soon.

In the meantime, you can always grab the latest Beta release here:
[**Snapshots (BETA)**](https://sourceforge.net/projects/lamexp/files/Snapshots%20%28BETA%29/)

This includes the latest Opus and Vorbis encoders. Development of Vorbis is pretty much dead (for a long time now), so don't expect any significant updates/improvements regarding Vorbis.

AAC encoder can **not** be included for legal reasons. The only decent AAC encoders that we have are **not** released under a license that would allow redistribution as part of LameXP.

Regards.

**Comment by expanse191** [comment]
Ok, thank you for answering to my question, hope you do release a new stable release soon, but I will try the beta release you suggested, thanks! By the way, you've done a great job on LameXP, it's very useful and easy to use, thanks!
