### ISSUE TITLE
Plays sound although configured not to

### ISSUE THREAD

**Issue by stonecrusher** [lordmulder/LameXP#86]
LameXP 4.17 Final-1 Build 2188
Win10x64 ver1909
Non-admin account

Reproduce:
1. Tools -> Configuration -> check "Disable Sound Effects".
2. Restart LameXP.
3. Popup "Urgent Update" "Your version of LameXP is more than a year old. Time for an update!" -> choose "Ignore".
4. Waiting music will play, but shouldn't.

**Comment by lordmulder** [comment]
Well, it _should_ play 😈 

We we blatantly ignore the "Disable Sound Effects" setting here, because this is intended to be sort of "annoying", in order to give people some incentive to actually **update** their version...

Now, why there is **_no_** update available at this time?

That is because I'm a bit late, this time around. So shame on me for that :cold_sweat:

New version will hopefully be released soon™.

Regards.

**Comment by stonecrusher** [comment]
Well it was more of a jumpscare for me, but I got the message 😄 
Oh and just a version bump without feature changes would do the trick!?

> released soon™

Trademark registered by Berlin Airport GmbH 😏

**Comment by BiatuAutMiahn** [comment]
Or when your kid is asleep.
I shouldn't have to mute the program through Window's sound mixer, or write my own implementation of this software in python to avoid dev that trolls his users lol.

imho, completely disabling the software as you once did if an update is available is more reasonable. Get rid of version expirations, some people don't have access to internet. If people don't update it's their fault, as a result they miss out on new features and/or bug fixes. The same thing tends to apply to pirates, if you pirate software don't expect help/support/updates/bug fixes.

**Comment by isidroco** [comment]
Music playing is totally unacceptable, I sometimes have recording sessions, and output is connected to high volume monitors. Opening lameXP would ruin that session and play a very loud sound. Popup is annoying but it won't ruin anything. PLEASE disable all sounds when that option is checked, (that should be default behaviour).
If one checked: Don't check for updates, shouldn't it mean that?  Sometimes I might want a particular old version, or simply don't want to test a new version until I'm ready: I don't update critical machines, sometimes it breaks things.

**Comment by BiatuAutMiahn** [comment]
I believe the older versions completely disable themselves

**Comment by lordmulder** [comment]
> If one checked: Don't check for updates, shouldn't it mean that? Sometimes I might want a particular old version, or simply don't want to test a new version until I'm ready: I don't update critical machines, sometimes it breaks things.

The regular automatic (every 14 days) update check *can* be disabled.

The warning about using a ***deprecated*** program version can't be skipped, an that is for a reason.

> I believe the older versions completely disable themselves

Only pre-release TEST builds will expire after 31 day . Regular releases *never* expire.

**Comment by lordmulder** [comment]
7179ad161ee9a9bc84cabbe02c7db1facc35dbf0
