### ISSUE TITLE
Possible to add support to insert 7z/zip songpacks?

### ISSUE THREAD

**Issue by Sa-Ja-Di** [lordmulder/LameXP#87]
Hello :) Just wondering, if it would be feasible to insert the possibility for some kind of 7z/zip songpack support?

Aka. drawing an archive into LameXP - with the program scanning/adding the songs - without the need to unpack and add the songs manually?

Thanks :D

**Comment by lordmulder** [comment]
Sorry, I have no plans for that at the moment.
