### ISSUE TITLE
Opus File Unsupported

### ISSUE THREAD

**Issue by RickSmedley** [lordmulder/LameXP#88]
Not sure if I'm doing something wrong but trying to convert an OPUS file to WAV and get a status of unsupported. I've tried mp3 as well and get the same thing. Sorry if this is simple or something I missed. If you want the file OPUS file please email me and I'll forward. Can't attach to this report.

**Comment by lordmulder** [comment]
Can you please provide the [***MediaInfo** report*](https://muldersoft.com/#mixp) for the "problematic" file?

**Comment by RickSmedley** [comment]
General
Complete name                            : D:\Sound\Studio 91\2020-2021 MJ Ideas\Sidewalk Prophets - Smile Lyrics.opus
Format                                   : WebM
Format version                           : Version 4
File size                                : 2.88 MiB
Duration                                 : 2 min 56 s
Overall bit rate                         : 137 kb/s
Writing application                      : google/video-file
Writing library                          : google/video-file
FileExtension_Invalid                    : webm

Audio
ID                                       : 1
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 2 min 56 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Comment by lordmulder** [comment]
So, this is a WebM file containing an Opus audio track.

Unfortunately, this combination is **not** currently supported, because we use `opusdec` from [Opus-Tools](http://opus-codec.org/downloads/) to decode Opus files.

**Comment by RickSmedley** [comment]
I Appreciate you getting back to me, not sure
      why a WebM file container with an Opus audio track can not be
      decoded as just an Opus audio track but I'm not the developer and
      I do appreciate your time looking into this.
    
      Rick Smedley
      717-377-5393
      
    
    On 2/27/2020 4:48 PM, LoRd_MuldeR
      wrote:
    
    
      
      So, this is a WebM file containing an Opus audio track.
      Unfortunately, this combination is not
        currently supported, because we use opusdec from Opus-Tools to decode Opus files.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lordmulder/LameXP/issues/88?email_source=notifications\u0026email_token=AOUEKTUZ6V7JFDXYBJWMO73RFAYMTA5CNFSM4KZTJT4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENGCTKQ#issuecomment-592193962",
"url": "https://github.com/lordmulder/LameXP/issues/88?email_source=notifications\u0026email_token=AOUEKTUZ6V7JFDXYBJWMO73RFAYMTA5CNFSM4KZTJT4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENGCTKQ#issuecomment-592193962",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lordmulder** [comment]
> I Appreciate you getting back to me, not sure why a WebM file container with an Opus audio track can not be decoded as just an Opus audio track but I'm not the developer and I do appreciate your time looking into this.

It is because the Opus audio format and the Opus Tools (`opusenc`, `opusdec`, etc.) as well as the Ogg container *all* were developed by the Xiph.Org Foundation. So, it is **not** much of a surprise that the ***default*** container format for Opus audio files is Ogg. The sames goes for Vorbis audio files, by the way.

WebM, on the other hand, was developed by Google Inc. in order to promote their VP8 and VP9 video formats. It combines the MKV (Matroska) container with the VP8 or VP9 video format and the Vorbis or Opus audio format.
