### ISSUE TITLE
Disable Updates / Disable Sound not working.

### ISSUE THREAD

**Issue by isidroco** [lordmulder/LameXP#89]
"Your version of LameXP is more than a year old. Time for an update!"
This keeps poping up, in spite of disable update setting. And whats worst, it emits annoying sound after ignoring update, again in spite having sounds disabled. That's unacceptable, I have a huge audio system with high volume. Sometimes I'm recording and sound from all software MUST be disabled. LameXP doesn't behave well.

**Comment by BiatuAutMiahn** [comment]
https://github.com/lordmulder/LameXP/issues/86

**Comment by lordmulder** [comment]
:point_right: 7179ad161ee9a9bc84cabbe02c7db1facc35dbf0
