### ISSUE TITLE
recent build does not convert to opus correctly

### ISSUE THREAD

**Issue by shorty66** [lordmulder/LameXP#9]
when converting to opus using build 1700 the resulting opus file is 2kB in size regardless of input and doesn't play using VLC.
Processing time is extremely short but varies with input file size: About 600ms for a 5mb mp3.

**Comment by lordmulder** [comment]
Works for me. Can you please post your **log** for the failed file?

**Comment by shorty66** [comment]
Yeah, sure. I'm sorry i didn't think of that:

LameXP v4.11 (Build #1700), compiled on 2015-04-05 at 18:27:08

-------------------------------

C:/Users/CHRIST~1/AppData/Local/Temp/df1da8b800b01cb4/lxp_mpg123.exe -v --utf8 -w C:\Users\CHRIST~1\AppData\Local\Temp\df1da8b800b01cb4\da3cbfd6bb9dae92.wav "C:\Users\Christian\Documents\Downloads\Marc-Uwe Kling - Das Känguru-Manifest\CD04\09 - Uljanow, Dschughaschwili und der Tanzbär.mp3"

High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
version 1.22.0; written and copyright by Michael Hipp and others
free software (LGPL) without any warranty but with best wishes
Decoder: SSE
Playing MPEG stream 1 of 1: C:\Users\Christian\Documents\Downloads\Marc-Uwe Kling - Das Känguru-Manifest\CD04\09 - Uljanow, Dschughaschwili und der Tanzbär.mp3 ...
MPEG 1.0, Layer: III, Freq: 44100, mode: Joint-Stereo, modext: 2, BPF : 626
Channels: 2, copyright: No, original: Yes, CRC: No, emphasis: 0.
Bitrate: 192 kbit/s Extension value: 0
Title: Uljanow, Dschughaschwili und der Tanzbär
Artist: Marc-Uwe Kling
Comment: Album: Das Känguru-Manifest
Year: 2011 Genre: Unknown
Note: Trying to resync...
Note: Skipped 366 bytes in input.
Warning: Encountered more data after announced end of track (frame 8068/8068). Frankenstein!
Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
MPEG 1.0, Layer: I, Freq: 48000, mode: Stereo, modext: 0, BPF : 32
Channels: 2, copyright: No, original: No, CRC: No, emphasis: 0.
Bitrate: 32 kbit/s Extension value: 1
[layer1.c:30] error: Illegal bit allocation value.
[layer1.c:171] error: Aborting layer I decoding after step one.
Note: Illegal Audio-MPEG-Header 0x656c6561 at offset 5061438.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
This was a Frankenstein track.
[1:04] Decoding of C:\Users\Christian\Documents\Downloads\Marc-Uwe Kling - Das Känguru-Manifest\CD04\09 - Uljanow, Dschughaschwili und der Tanzbär.mp3 finished.

Exited with code: 0x0000

-------------------------------

C:/Users/CHRIST~1/AppData/Local/Temp/df1da8b800b01cb4/lxp_sox.exe --i C:\Users\CHRIST~1\AppData\Local\Temp\df1da8b800b01cb4\da3cbfd6bb9dae92.wav

Input File : 'C:\Users\CHRIST~1\AppData\Local\Temp\df1da8b800b01cb4\da3cbfd6bb9dae92.wav'
Channels : 2
Sample Rate : 48000
Precision : 16-bit
Duration : 00:00:00.01 = 384 samples ~ 0.6 CDDA sectors
File Size : 1.58k
Bit Rate : 1.58M
Sample Encoding: 16-bit Signed Integer PCM

Exited with code: 0x0000

-------------------------------

C:/Users/CHRIST~1/AppData/Local/Temp/df1da8b800b01cb4/lxp_opusenc.exe --vbr --comp 10 --framesize 20 --bitrate 96 --title "Uljanow, Dschughaschwili und der Tanzbär" --artist "Marc-Uwe Kling" --album "Das Känguru-Manifest" --genre Hoerbuch --date 2011 --comment tracknumber=1 --comment "comment=Kodiert mit LameXP" C:\Users\CHRIST~1\AppData\Local\Temp\df1da8b800b01cb4\da3cbfd6bb9dae92.wav "C:\Users\Christian\Music\09 - Uljanow, Dschughaschwili und der Tanzbär (2).opus"

Encoding using libopus 1.1.x-git SSE2 [2015-03-26] (audio)
-----------------------------------------------------
Input: 48kHz 2 channels
Output: 2 channels (2 coupled)
20ms packets, 96kbit/sec VBR
Preskip: 312
Encoding complete
-----------------------------------------------------
Encoded: 0.02 seconds
Runtime: 1e-006 seconds
(2e+004x realtime)
Wrote: 1128 bytes, 1 packets, 3 pages
Bitrate: 1.2kbit/s (without overhead)
Instant rates: 1.2kbit/s to 1.2kbit/s
(3 to 3 bytes per packet)
Overhead: 99.7% (container+metadata)

Exited with code: 0x0000

**Comment by lordmulder** [comment]
So it's actually a problem in the **decoding** stage:

	Note: Trying to resync...
	Note: Skipped 366 bytes in input.
	Warning: Encountered more data after announced end of track (frame 8068/8068). Frankenstein!
	Warning: Big change from first (MPEG version, layer, rate). Frankenstein stream?
	MPEG 1.0, Layer: I, Freq: 48000, mode: Stereo, modext: 0, BPF : 32
	Channels: 2, copyright: No, original: No, CRC: No, emphasis: 0.
	Bitrate: 32 kbit/s Extension value: 1
	[layer1.c:30] error: Illegal bit allocation value.
	[layer1.c:171] error: Aborting layer I decoding after step one.
	Note: Illegal Audio-MPEG-Header 0x656c6561 at offset 5061438.
	Note: Trying to resync...
	Note: Hit end of (available) data during resync.
	This was a Frankenstein track.

This almost certainly means that your **input** MP3 file is corrupted/invalid.

But you can try yourself:
    mpg123.exe -w "output.wav" "your_input.mp3"

Download mpg123.exe from here, for example:
http://mpg123.de/download/win32/mpg123-1.22.0-x86.zip

**Comment by shorty66** [comment]
I did not create the original file. As it plays just fine with several different players i was not suspecting it to be corrupted. I will try to convert it otherwise in order to be able to convert it to opus.
Thanks for the help. 
I think this issue can be closed then...

**Comment by lordmulder** [comment]
Players are pretty robust to deal with all sorts of f*ckd up streams. So just because "it plays" or just because you didn't notice any serious issues while playing it, this doesn't mean the stream is valid/correct. Again, I suggest you try with **MPEG Audio Info** (see link above) or [**MP3val**](http://mp3val.sourceforge.net/index.shtml) to check the stream.
