### ISSUE TITLE
"Overwrite Existing File" Does not work as expected

### ISSUE THREAD

**Issue by jbax1899** [lordmulder/LameXP#93]
I eventually found the answer to this myself after a bit of digging. My issue was the same as this person: [Files not being Overwrited (when ussing Same folder as the input) #76](https://github.com/lordmulder/LameXP/issues/76)

In the changelog under v4.10 it says: "Fixed "overwrite existing file" mode to NOT delete the input file"

I understand that technically it isn't possible to overwrite a file as it is being loaded. Though, I assume, you can create the new file and delete the old one.

The only way to do what I want that I know of is to use a rename pattern, append a special character, use Bulk Rename Utility to search and delete the files without the special character and then rename the ones with. But of course this seems a bit much.

**Comment by lordmulder** [comment]
Why not output to a new (sub)folder? You can easily move the files from that folder to the "original" folder and replace it's content later on. Any standard file manager will do this with one drag&drop operation.
