### ISSUE TITLE
Feature Request / Convert .M4A

### ISSUE THREAD

**Issue by AzzaAzza69** [lordmulder/LameXP#95]
The explorer menu offered me a "Convert this file with LameXP 4.18" but after pressing Encode Now! it says unsupported :(

**Comment by lordmulder** [comment]
Windows offers **very** limited support to "link" an application to a file type. In fact, you can only "link" your application to a certain ***file extension***, such as `*.mp3`, `*.m4a` and so on. Whether that file is actually "supported" by my application will **not** be known until you actually try to open that file.

**Comment by AzzaAzza69** [comment]
I completely agree. I hadn't thought that it could be the file content not matching the extension. 
The error message lead me to believe the problem was possibly that you had linked the .m4a to the program but it didn't handle .m4a and not that the file content did not match the extension. Ok. My mistake.

PS. Does your update check only see if the year is different as I vaguely remember it activating in Jan 2020 but the build is Dec 2019?
PPS. The "Please wait - skipping update check" also ignores the [x] Disable sound effects and plays a tune.

**Comment by lordmulder** [comment]
I suggest you throw the "problematic" file at MediaInfo to get some info on the real contents:
http://muldersoft.com/#mixp
